-- Messaging tables are now defined in schema.sql
-- This file is kept for reference only. Do NOT run this separately.
-- All messaging-related tables (messages, conversations, message_attachments)
-- are included in schema.sql.
