-- Payment tables are now defined in schema.sql
-- This file is kept for reference only. Do NOT run this separately.
-- All payment-related tables (payments, mpesa_requests, payment_callbacks)
-- are included in schema.sql with corrected foreign key references to bookings(id).
